# 데이터 전처리

1. 레이블 인코딩 

In [1]:
from sklearn.preprocessing import LabelEncoder

In [2]:
items = ['TV','냉장고','전자레인지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서']

In [3]:
# 방법 1)
# 객체 생성 
le = LabelEncoder()

In [4]:
# 학습할 데이터 훑어 봄
le.fit(items)

LabelEncoder()

In [7]:
# 인코딩 실행 
labels = le.transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [8]:
# 방법 2)
# 실전에서는 
le2 = LabelEncoder()
labels = le2.fit_transform(items) # 학습과 label 인코딩 한번에 수행 
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [9]:
# 방법 3)
# 고수들은
labels = LabelEncoder().fit_transform(items)
labels

array([0, 1, 4, 5, 3, 3, 2, 2])

In [10]:
# decoding (디코딩) 
le.inverse_transform([2,4,3,0,5,1]) 

array(['믹서', '전자레인지', '선풍기', 'TV', '컴퓨터', '냉장고'], dtype='<U5')

### 2. `One-hot-encoding`

In [ ]:
# 머신러닝에서는 안쓰이지만 딥러닝에서는 반드시 쓰임! 
# 딥러닝을 0,1 두개밖에 없음
# 딥러닝에서 0=[1,0,0], 1=[0,1,0], 2=[0,0,1]

# 레이블 인코딩 -> 원핫인코딩

In [11]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
oh_labels = ohe.fit_transform(labels.reshape(-1,1)) # 2차원 데이터로 변환 
oh_labels.toarray() # 결과 보기위해 toarray() -> compressed 되어있어서


array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [13]:
# 참고)
from tensorflow.keras.utils import to_categorical # 로컬에서는 따로 설치해야함! 코랩은 그냥 가능 
to_categorical(labels)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]], dtype=float32)

### 3. 표준화
- 평균=0, 표준편차=1 인 가우시간 정규분포

In [15]:
from sklearn.datasets import load_iris
iris = load_iris()

In [17]:
from sklearn.preprocessing import StandardScaler
iris_std = StandardScaler().fit_transform(iris.data) # 표준편차

In [19]:
import pandas as pd
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [20]:
# 표준편차(STD) 
df = pd.DataFrame(iris_std, columns=iris.feature_names)
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count       1.500000e+02      1.500000e+02       1.500000e+02   
mean       -1.690315e-15     -1.842970e-15      -1.698641e-15   
std         1.003350e+00      1.003350e+00       1.003350e+00   
min        -1.870024e+00     -2.433947e+00      -1.567576e+00   
25%        -9.006812e-01     -5.923730e-01      -1.226552e+00   
50%        -5.250608e-02     -1.319795e-01       3.364776e-01   
75%         6.745011e-01      5.586108e-01       7.627583e-01   
max         2.492019e+00      3.090775e+00       1.785832e+00   

       petal width (cm)  
count      1.500000e+02  
mean      -1.409243e-15  
std        1.003350e+00  
min       -1.447076e+00  
25%       -1.183812e+00  
50%        1.325097e-01  
75%        7.906707e-01  
max        1.712096e+00

- `Logistic Regression`으로 분류

In [22]:
from sklearn.linear_model import LogisticRegression
lrc = LogisticRegression(random_state=2022)

In [26]:
from sklearn.model_selection import train_test_split
X_trian, X_test, y_train, y_test = train_test_split(iris.data, iris.target,
                                                    stratify = iris.target, random_state=2022)


In [27]:
lrc.fit(X_trian, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression(random_state=2022)

In [28]:
# 표준정규분포로 변환된 데이터로 학습하면 빨리 목표값에 도달헤서 에러가 발생하지 않음!
from sklearn.model_selection import train_test_split
X_trian, X_test, y_train, y_test = train_test_split(iris_std, iris.target,
                                                    stratify = iris.target, random_state=2022)

In [29]:
lrc.fit(X_trian, y_train)

LogisticRegression(random_state=2022)

In [30]:
lrc.score(X_test, y_test)

0.9473684210526315

### 4. 정규화
- 최소값=0, 최대값=1 로 변환

In [36]:
from sklearn.preprocessing import MinMaxScaler
iris_mm = MinMaxScaler().fit_transform(iris.data)

In [34]:
import pandas as pd
df = pd.DataFrame(iris_mm, columns=iris.feature_names)
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            0.428704          0.440556           0.467458   
std             0.230018          0.181611           0.299203   
min             0.000000          0.000000           0.000000   
25%             0.222222          0.333333           0.101695   
50%             0.416667          0.416667           0.567797   
75%             0.583333          0.541667           0.694915   
max             1.000000          1.000000           1.000000   

       petal width (cm)  
count        150.000000  
mean           0.458056  
std            0.317599  
min            0.000000  
25%            0.083333  
50%            0.500000  
75%            0.708333  
max            1.000000

In [35]:
from sklearn.model_selection import train_test_split
X_trian, X_test, y_train, y_test = train_test_split(iris_mm, iris.target,
                                                    stratify = iris.target, random_state=2022)

In [41]:
lrc = LogisticRegression(random_state = 2022)
lrc.fit(X_trian, y_train)
lrc.score(X_test, y_test)

0.9210526315789473